@startuml
left to right direction
actor "Admin" as Admin
actor "Librarian" as Librarian
actor "Student/Member" as Member

usecase "User Authentication" as UC1
usecase "Manage User Accounts" as UC2
usecase "Search User Information" as UC3
usecase "Reset Password" as UC4

Admin --> UC1
Admin --> UC2
Librarian --> UC1
Librarian --> UC3
Member --> UC1
Member --> UC4
@enduml
