@startuml
class Book {
  + bookID: String
  + title: String
  + author: String
  + ISBN: String
  + category: String
  + isAvailable: Boolean
}

class Admin {
  + addBook(book: Book): Boolean
  + editBook(bookID: String): Boolean
  + deleteBook(bookID: String): Boolean
}

class Librarian {
  + searchBook(query: String): List<Book>
  + checkAvailability(bookID: String): Boolean
}

Book <.. Admin
Book <.. Librarian
@enduml
